### ISSUE TITLE
串口接收区文字尺寸无法通过qss文件调整

### ISSUE THREAD

**Issue by liyang5945** [Neutree/COMTool#132]
我使用的是17寸1080P的笔记本电脑，感觉串口接收区的文字太小了，尝试修改qss文件来调整文字大小，修改的应该是正确的位置，背景色改为#3a3a55已经生效，尝试添加font-size: 20px; 字体没有变化，另外希望添加类似ubuntu终端类似的功能，按住ctlt+调整鼠标滚轮来调节文字大小
```css
QTextEdit, QPlainTextEdit, QListView {
    background-color: #3a3a55;
    border: 2px solid #3a3a3a;
    border-radius: 5px;
    background-attachment: scroll;
    font-size: 20px;
}
```
![20240403_163944](https://github.com/Neutree/COMTool/assets/23631026/bc72ca64-bbf8-4fe0-ae4d-b7d1ba3b0507)
